name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        zerotier_version: ['1.8.4', '1.8.5']
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build zerotier --build-arg VERSION=${{ matrix.node_version }} --tag altano/zerotier:v${{ matrix.node_version }}_d$(date +%s)
