name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        zerotier_version: ['1.8.4', '1.8.5']
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file zerotier/Dockerfile --tag altano/zerotier:${{ matrix.node_version }}_$(date +%s)
